<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Data.SqlClient">
      <HintPath>..\..\bin\Debug\net10.0\runtimes\win\lib\net9.0\Microsoft.Data.SqlClient.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.SqlClient.Extensions.Abstractions">
      <HintPath>..\..\bin\Debug\net10.0\Microsoft.Data.SqlClient.Extensions.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.SqlClient.Internal.Logging">
      <HintPath>..\..\bin\Debug\net10.0\Microsoft.Data.SqlClient.Internal.Logging.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
